


<a href="" id="mobile"> <button class="hamburger">&#9776;</button></a>

<nav id="acceuil">
<!--
    <ul>
-->
    <li>
        <a href="index.php?page=home"><i class="fa fa-home fa-3x" aria-hidden="true"></i><p>Accueil</p></a>

    </li>
        <li>
            <a href="index.php?page=presentation"><i class="fa fa-user fa-3x" aria-hidden="true"></i><p>Quelques  mots sur moi</p></a>

        </li>

         <li>
             <a href="index.php?page=projets"><i class="fa fa-code fa-3x" aria-hidden="true"></i><p>Mes projets</p></a>

         </li>
         <li>

             <a href="index.php?page=contact"><i class="fa fa-envelope-o fa-3x" aria-hidden="true"></i><p>On reste en contact</p></a>

        </li>
        <li>

            <a href="index.php?page=avis"><i class="fa fa-book fa-3x" aria-hidden="true"></i><p>Avis</p></a>

        </li>
<!--
    </ul>
-->

</nav>

