<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="assets/css/style.css" >
    <title>Title</title>
</head>
<main>
    <?php foreach ($aMail as $value){?>
        <p><?=htmlspecialchars($value['mail'])?></p>
        <p><?=nl2br(htmlspecialchars($value['message']))?></p>


        <input type="button" id="repondre" value="répondre">
            <div class="mail" style="display: none">
                <form method="post" action="">
                    <input type="hidden" name="mail" value="<?=htmlspecialchars($value['mail'])?>">
                    <input type="text" name="Sujet" placeholder="Sujet"></br></br>
                    <textarea name="reponse"></textarea></br></br>
                    <input type="submit" name="message" value="Envoyer">
                </form>

            </div>
    <?php }?>
</main>
<script src="assets/js/mail.js"></script>
</body>
</html>