<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.css" />
    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>

    <link rel="stylesheet" href="assets/css/style.css" >
    <title>Projets</title>
</head>
<body>
        <div id="menu">
            <?php include 'header.phtml' ?>
        </div>
    <main>
        <?php include 'search.phtml'?>
            <?php foreach ($aArticleFull as $value){?>
                <section>

                    <h1><?= htmlspecialchars($value["titre"]);?></h1>





                    <p><?= nl2br($value["contenu"]);?></p>
                </section>
            <?php }?>
<h2><?=htmlspecialchars($articleabs)?></h2>


            <button><a href="index.php?page=projets">Retour</a></button>


    </main>
<footer>
    <p>Ce site a été crée par Arnaud Escalier. Les photos utilisées pour ce site sont libre de droit</p>
</footer>
<script type="text/javascript" src="assets/js/function.js"></script>
</body>
</html>