<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.css" />
    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="assets/css/style.css" >
    <title>Contact</title>
</head>
<body>
        <div id="menu">
            <?php include 'php/views/header.phtml' ?>
        </div>
    <main>
       <section>

            <h1>On reste en contact?</h1>

            <form method="post" action="">
                <p><input type="text" name="nom" placeholder="Votre nom" value="<?php if (!empty($_POST["nom"])) { echo stripcslashes(htmlspecialchars($_POST["nom"],ENT_NOQUOTES)); } ?>" /></p>
                <p><input type="text" name="prenom" placeholder="Votre prénom" value="<?php if (!empty($_POST["prenom"])) { echo stripcslashes(htmlspecialchars($_POST["prenom"],ENT_NOQUOTES)); } ?>" /></p>
                <p><input type="email" name="mail" placeholder="Votre email" /></p>
                 <textarea name="message" rows="10" cols="50" placeholder="Votre message" value="value="<?php if (!empty($_POST["message"])) { echo stripcslashes(htmlspecialchars($_POST["message"],ENT_NOQUOTES)); } ?>">

               </textarea></br>
                <input type="submit" name="contact">
            </form>
       </section>



    </main>
<footer>
    <p>Ce site a été crée par Arnaud Escalier. Les photos utilisées pour ce site sont libre de droit</p>
</footer>
<script type="text/javascript" src="assets/js/function.js"></script>
</body>
</html>